#color detection...(Dazed off for a sec there was listening to Last son composed by John Williams and David Flemming so you understand why; it's a great song beutiful)
#Anywhoo from what I am learning about color detection is that it is a technique used in computer vision to identify and locate specific colors within an image or video stream. This can be useful for a variety of applications, such as object tracking, image segmentation, and even in robotics for tasks like sorting objects based on color.
#Crucial aspect of image processing and computer vision, and it can be implemented using various algorithms and techniques. One common approach is to convert the image from the RGB color space to a different color space, such as HSV (Hue, Saturation, Value), which can make it easier to isolate specific colors based on their hue and saturation values.
#So whether ddeveloping a robot that can identify objects or creating a tool for color based image analysis or just playing around with image manipulation, detecting and identifying colors can be very useful.(I do not see concretely how though)

#colors in digital images are typically represented using the RGB color space model, where each pixel is defined by its red, green, and blue components. Each component can have a value ranging from 0 to 255, which allows for a wide range of colors to be represented. For example, pure red would be represented as (255, 0, 0), pure green as (0, 255, 0), and pure blue as (0, 0, 255). By manipulating these values, you can create various colors and shades in digital images.
#However when it comes to color detection, it can be more effective to use a different color space, such as HSV (Hue, Saturation, Value), because it separates the color information (hue) from the intensity information (saturation and value;brightness). This can make it easier to identify specific colors based on their hue values, regardless of lighting conditions or intensity. For example, in the HSV color space, pure red would have a hue value of around 0 degrees, pure green would have a hue value of around 120 degrees, and pure blue would have a hue value of around 240 degrees. By setting thresholds for the hue values, you can effectively detect and isolate specific colors in an image.

#Steps I will be personally taking to implement color detection in Python using OpenCV:
#1. Import necessary libraries: I will need to import OpenCV and NumPy for image processing tasks.
#2. Read the image: I will load the image in which I want to detect colors
#3. Convert the color space: I will convert the image from the RGB color space to the HSV color space using OpenCV's cvtColor function.
#4. Define color range for detection: I will specify the lower and upper bounds for the hue, saturation, and value (HSV) to define the range of colors I want to detect.
#5. Create a mask for the defined color: I will use the inRange function to create a binary mask that highlights the areas of the image that fall within the specified color range.
#6 Creating contours, applying and tracking masks, and adding text
#7. Running the program and displaying the results: I will use OpenCV's imshow function to display the original image with the detected colors highlighted, and I may also display the mask to visualize which areas of the image are being detected.

#importing libraries in reading the image
import cv2
import numpy as np

#turning on the camera
webcam = cv2.VideoCapture(0)

#converting the color space to HSV
while True:
    _, imageFrame = webcam.read() #Do not understand the underscore comma, but I think it is a common convention in Python to use an underscore as a placeholder for a variable that is not going to be used. In this case, the read() function returns two values: 
    #a boolean indicating whether the frame was successfully read, and the actual image frame itself. Since we are only interested in the image frame, we can ignore the boolean value by assigning it to an underscore. 
    #But wait if the read function returns 2 values should it not be an array? I guess it is a tuple, which is a data structure in Python that can hold multiple values. In this case, the read() function returns a tuple containing the boolean value and the image frame. By using the underscore, we are effectively ignoring the first value in the tuple and only keeping the second value, which is the image frame that we want to process.
    #Remind me to look into tuples and how they work in Python, I have a basic understanding but I want to deepen my knowledge on them.

    #converting the color space from BGR to HSV wait why is it BGR and not RGB? I thought it was RGB? I guess OpenCV uses BGR by default for some reason
    hsvFrame = cv2.cvtColor(imageFrame, cv2.COLOR_BGR2HSV)
    #so thecvtColor is a function in the cv2 module or is it library? I think it is a function that is used to convert an image from one color space to another. In this case, we are converting the image from the BGR color space (which is the default color space used by OpenCV) to the HSV color space. 
    #The cv2.COLOR_BGR2HSV is a constant that specifies the type of conversion we want to perform, which in this case is from BGR to HSV. By using this function, we can easily convert the image to the HSV color space, which can make it easier to detect specific colors based on their hue and saturation values.
    #the function takes how many arguments? I see it takes 2 arguments, the first one is the image we want to convert and the second one is the type of conversion we want to perform. So in this case, we are passing the imageFrame as the first argument and cv2.COLOR_BGR2HSV as the second argument to specify that we want to convert from BGR to HSV color space.
    #what other type of conversions does the function support? I know it supports a variety of conversions, such as RGB to Grayscale, RGB to YUV, and many more. I will have to look into the documentation to see all the different types of conversions that are supported by the cvtColor function.

    #Defining the lower and upper bounds for the color detection that is I define the color ranges for the colors I want to detect. For example, if I want to detect red color, I can define the lower and upper bounds for the hue, saturation, and value (HSV) as follows:

    #setting range for red color
    red_lower = np.array([136, 87, 111], np.uint8)
    red_upper = np.array([180, 255, 255], np.uint8)
    #so the np.array is a function in the NumPy library that is used to create an array. In this case, we are creating two arrays, red_lower and red_upper, which define the lower and upper bounds for the hue, saturation, and value (HSV) for the red color. The values in the arrays represent the minimum and maximum values for each of the HSV components that we want to detect. By defining these bounds, we can create a mask that highlights the areas of the image that fall within this color range.
    #But who defines the values for the lower and upper bounds? I assume it is based on experimentation and observation. I can use a color picker tool to find the HSV values for the specific shade of red I want to detect, and then adjust the lower and upper bounds accordingly to ensure that I am capturing the desired range of colors.
    #Also I understand that the np.uint8 is a data type that specifies that the values in the array should be treated as unsigned 8-bit integers, which means they can range from 0 to 255. This is important because the HSV values for hue, saturation, and value are typically represented as integers in this range, so using np.uint8 ensures that the values are correctly interpreted when we create the mask for color detection.
    #Another Question I have is for red for example what is the difference between [136, 87, 111] and maybe others are these values universally fixed for red lower bound? I think they can vary depending on the specific shade of red you want to detect and the lighting conditions in the image. The values for the lower and upper bounds can be adjusted based on experimentation to ensure that you are capturing the desired range of colors. So while there may be some general guidelines for the HSV values for red, it is not necessarily fixed and can be fine-tuned based on your specific use case and the characteristics of the images you are working with.
    #But I thought we are using HSV because it is not affected by lighting conditions, so why would we need to adjust the values based on lighting? I guess while HSV can help mitigate some of the effects of lighting, it is not completely immune to it. Different lighting conditions can still affect the appearance of colors in an image, and as a result, you may need to adjust the lower and upper bounds for color detection to account for these variations. For example, under different lighting conditions, the same shade of red may appear slightly different in terms of its hue and saturation values, so you may need to fine-tune the bounds to ensure that you are accurately detecting the desired color range in various lighting scenarios.

    #defineing the mask for red color
    red_mask = cv2.inRange(hsvFrame, red_lower, red_upper)
    #the inRange function is a function in the OpenCV library that is used to create a binary mask based on the specified lower and upper bounds for color detection. In this case, we are using the inRange function to create a mask for the red color by passing the HSV image (hsvFrame) and the defined lower and upper bounds (red_lower and red_upper) as arguments. The function will return a binary mask where the pixels that fall within the specified color range will be set to 255 (white), and the pixels that do not fall within the range will be set to 0 (black). This mask can then be used to isolate and highlight the areas of the image that contain the red color we want to detect.
    #Having a hard time the concept of a mask and why it is called binary, I understand that it is a binary image because it only contains two values (0 and 255), but I am not sure why it is called a mask. I think it is called a mask because it acts as a filter that allows us to isolate specific parts of the image based on the color we want to detect. By applying the mask to the original image, we can effectively "mask out" the areas that do not contain the desired color, leaving us with only the regions of interest that we want to analyze further. So in this sense, the mask serves as a tool to focus our attention on specific colors in the image while ignoring the rest. Also is the mask based on thebounds we set for the color detection?
    # After looking it up, Yes, the mask is directly based on the lower and upper bounds we defined for the color detection. The inRange function uses these bounds to determine which pixels in the HSV image fall within the specified color range, and it creates the binary mask accordingly. So if we adjust the bounds, we will see a different mask that highlights different areas of the image based on the new color range we have defined.

    #green color
    green_lower = np.array([25, 52, 72], np.uint8)
    green_upper = np.array([102, 255, 255], np.uint8)
    green_mask = cv2.inRange(hsvFrame, green_lower, green_upper)

    #blue color
    blue_lower = np.array([94, 80, 2], np.uint8)
    blue_upper = np.array([120, 255, 255], np.uint8) #what would be different if I set Hue to 126 instead of the 120? I think it would allow us to detect a slightly wider range of blue colors, including some shades that may have a hue value around 126. By increasing the upper bound for the hue, we can capture a broader spectrum of blue colors in the image, which may be beneficial if we want to ensure that we are detecting all relevant shades of blue. However, it is important to be cautious when adjusting the bounds, as setting them too wide may result in false positives and include colors that are not actually blue. So it is a balance between capturing the desired range of colors and avoiding unwanted detections.
    blue_mask = cv2.inRange(hsvFrame, blue_lower, blue_upper)

    #combining the masks, what even is that and why do we need to combine them? I think combining the masks allows us to create a single mask that highlights all the colors we want to detect in the image. By using a bitwise OR operation (cv2.bitwise_or), we can combine the individual masks for red, green, and blue into one comprehensive mask that captures all the specified color ranges. This way, we can easily apply this combined mask to the original image to isolate and analyze all the relevant colors in one step, rather than having to apply each mask separately.
    #why not bitwise AND? I think using a bitwise AND operation would not be appropriate in this case because it would only highlight the pixels that are common to all the masks, which means we would only detect the colors that fall within the intersection of the defined color ranges. This would likely result in very few detections, as it is unlikely that many pixels will simultaneously meet the criteria for being red, green, and blue at the same time. On the other hand, using a bitwise OR operation allows us to capture any pixel that falls within any of the defined color ranges, giving us a more comprehensive detection of all the relevant colors in the image.
    #Let me start with bitwise and and see what happens, I want to see the difference between the two operations in terms of the resulting mask and the colors that are detected. This will help me understand the practical implications of using bitwise AND versus bitwise OR for combining the masks in color detection.

    #creating mask
    
    #to detect only that particular color
    kernel = np.ones((5, 5), "uint8") #what is a kernel and why do we need it? I think a kernel is a small matrix that is used in image processing to perform operations such as blurring, sharpening, and edge detection. In the context of color detection, we can use a kernel to apply morphological operations to the mask, such as dilation or erosion, which can help to improve the quality of the mask by filling in gaps or removing noise. By applying these operations with the kernel, we can enhance the detected regions of color and make them more distinct in the resulting image.

    #dilation is a morphological operation that can be applied to the mask to enhance the detected regions of color. It works by adding pixels to the boundaries of the detected regions, effectively expanding them. This can help to fill in small gaps or holes in the detected areas, making them more solid and easier to analyze. By applying dilation with a kernel, we can improve the visibility of the detected colors in the image and make it easier to identify and track them.
    red_mask = cv2.dilate(red_mask, kernel) #so dilate takes the mask and the kernel as arguments and applies the dilation operation to the mask using the specified kernel. The result is an enhanced version of the red_mask where the detected regions of red color are expanded, making them more prominent in the resulting image. This can help to improve the accuracy of color detection by ensuring that we capture all relevant areas of the image that contain the desired color.
    #So the kernel is an array? Yes, the kernel is a small matrix (in this case, a 5x5 array of ones) that is used to define the neighborhood for the dilation operation. The values in the kernel determine how the dilation is applied to the mask, with the ones indicating which pixels should be considered for expansion during the dilation process. By using this kernel, we can control the extent of dilation and how it affects the detected regions of color in the mask.
    #Trying to find oout what happens if I change the size of the kernel, for example to (3, 3) or (7, 7). I want to see how it affects the dilation process and the resulting mask. A smaller kernel may result in less expansion of the detected regions, while a larger kernel may lead to more significant dilation, potentially filling in larger gaps but also increasing the risk of merging nearby regions together. By experimenting with different kernel sizes, I can find the optimal balance for enhancing the detected colors without losing important details or creating unwanted connections between separate regions.
    res_red = cv2.bitwise_and(imageFrame, imageFrame, mask = red_mask) #what does the bitwise_and function do in this context? I think the bitwise_and function is used to apply the red_mask to the original image (imageFrame) in order to isolate and highlight the detected red regions. By performing a bitwise AND operation between the original image and itself, while using the red_mask as a filter, we can effectively keep only the pixels that correspond to the detected red color, while setting all other pixels to black. This results in an image (res_red) that contains only the areas of the original image where the red color was detected, allowing us to focus on those specific regions for further analysis or visualization.
    #So the bitwise_and function takes the original image twice as arguments along with the mask, and it applies the mask to the image to produce a new image that highlights only the detected color regions. This is a common technique in image processing to isolate specific features based on a binary mask, allowing us to analyze or display only the relevant parts of the image that contain the desired color. By using bitwise AND, we ensure that only the pixels that are both in the original image and in the mask (i.e., the detected color regions) are retained in the resulting image. I however do not see the use of dilation here, I thought it was supposed to enhance the detected regions, but it seems like we are just applying the mask to the original image without any visible effect from the dilation. 
    # TODO:I will have to experiment with the dilation and see how it affects the resulting image when we apply the mask. It may be that the dilation is helping to fill in gaps in the mask, which can improve the overall detection of the color regions, but I will need to see it in action to fully understand its impact on the final result.

    #green
    green_mask = cv2.dilate(green_mask, kernel)
    res_green = cv2.bitwise_and(imageFrame, imageFrame, mask = green_mask)

    #blue
    blue_mask = cv2.dilate(blue_mask, kernel)
    res_blue = cv2.bitwise_and(imageFrame, imageFrame, mask = blue_mask)

    #creating contours to track the detected colors(creating contours, tracking masks, and adding text)
    #Find out what a contour is and how it is used in this context. I think a contour is a curve that joins all the continuous points along a boundary that have the same color or intensity. In the context of color detection, contours can be used to identify and track the shapes of the detected color regions in the image. By finding contours in the binary mask created for each color, we can determine the location and shape of the detected areas, which can be useful for further analysis or for drawing bounding boxes around the detected colors in the original image. Contours help us to visualize and understand the spatial distribution of the detected colors within the image.

    #creating contours for red color
    contours, hierarchy = cv2.findContours(red_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) #what does the findContours function do? I think the findContours function is used to detect and retrieve the contours from the binary mask (red_mask) that we created for the red color. It takes the mask as input and returns a list of contours and their hierarchy. The contours are essentially the boundaries of the detected color regions in the mask, and they can be used to analyze the shape and location of these regions in the original image. By using findContours, we can identify the specific areas where the red color is present and potentially draw bounding boxes or other shapes around them for visualization or further processing.
    #The cv2.RETR_TREE is a contour retrieval mode that retrieves all the contours and reconstructs a full hierarchy of nested contours. This means that it will retrieve not only the outer contours but also any contours that are contained within other contours, allowing us to understand the relationship between different detected regions in the image. The cv2.CHAIN_APPROX_SIMPLE is a contour approximation method that compresses horizontal, vertical, and diagonal segments and leaves only their end points. This can help to reduce the number of points in the contour representation, making it more efficient for processing while still retaining the essential shape information of the detected color regions.
    #So since I was to learn more about tuples as mentioned above there somewhere and we have 2 variables on the left side of the assignment, does that mean that the findContours function returns a tuple containing the contours and their hierarchy? After digging, Yes, that is correct. The findContours function returns a tuple where the first element is a list of contours and the second element is the hierarchy of those contours. By unpacking this tuple into the variables contours and hierarchy, we can easily access both the contours and their hierarchical relationships for further processing in our color detection application.
    for pic, contour in enumerate(contours):#EXplanation: The enumerate function is used to loop through the contours list while keeping track of the index (pic) of each contour. This allows us to access both the contour itself and its corresponding index in the list, which can be useful for various purposes such as labeling or debugging. By using enumerate, we can easily iterate over the contours and perform operations on each one while also having access to their indices if needed.
        area = cv2.contourArea(contour) #what does the contourArea function do? Found out that the contourArea function is used to calculate the area of a given contour. It takes a contour as input and returns a scalar value representing the area enclosed by that contour. This can be useful for filtering contours based on their size, allowing us to focus on larger or smaller detected regions depending on our specific requirements for color detection.
        if(area > 300): #why are we checking if the area is greater than 300? Well from a medium post, I think we are checking if the area is greater than 300 to filter out small contours that may be caused by noise or irrelevant details in the image. By setting a threshold for the area, we can ensure that we are only considering contours that represent significant detected color regions, which can help to improve the accuracy and relevance of our color detection results. This way, we can focus on larger, more meaningful contours that are likely to correspond to actual objects or areas of interest in the image, rather than being distracted by small, insignificant contours that may not be relevant to our analysis.
            x, y, w, h = cv2.boundingRect(contour) #the boundingRect function is used to calculate the bounding rectangle for a given contour. It takes a contour as input and returns the coordinates (x, y) of the top-left corner of the rectangle, as well as its width (w) and height (h). This can be useful for drawing a rectangle around the detected color region in the original image, allowing us to visually highlight and identify the location of the detected colors more easily. wait the rectangle, omds maybe this is the bounding box I see on peoples cool projects, I have seen people draw bounding boxes around detected objects in images and videos, and this is likely how they are doing it by using the boundingRect function to get the coordinates and dimensions of the rectangle that can be drawn around the detected contour.
            imageFrame = cv2.rectangle(imageFrame, (x, y), (x + w, y + h), (0, 0, 255), 2) #the rectangle function is used to draw a rectangle on the original image (imageFrame) using the coordinates and dimensions obtained from the boundingRect function. The first argument is the image on which to draw the rectangle, the second argument is the top-left corner of the rectangle (x, y), the third argument is the bottom-right corner of the rectangle (x + w, y + h), the fourth argument is the color of the rectangle in BGR format (in this case, red), and the fifth argument is the thickness of the rectangle's border. By using this function, we can visually highlight the detected color regions in the original image by drawing rectangles around them based on their contours. Meaning this is the bounding box actual function the boundrect is just to get the coordinates and dimensions, while the rectangle function is what actually draws the bounding box on the image.
            #Trying to understand the top left bottom right stuff so top left is already determined in the library as (x,y) w is width and h is height so to get the bottom right corner we add the width to x and the height to y, which gives us the coordinates for the bottom right corner of the rectangle. This way, we can accurately draw the rectangle around the detected contour by specifying both corners based on the dimensions of the bounding box. but I thought y + h would give us a top or can h be negative? Oh wait I guess h cannot be negative because it represents the height of the rectangle, which is always a positive value. So by adding h to y, we are  getting the coordinates for the bottom right corner of the rectangle, as it extends downward from the top left corner defined by (x, y). This allows us to correctly position the rectangle around the detected contour in the image.
            #That was a dumb question lol 😂

            cv2.putText(imageFrame, "Yay Red Colour, hmm Fire bender? Oh oh The red Mystical ranger hihi", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 0, 255)) #the putText function is used to add text to the original image (imageFrame) at the specified location. In this case, I am  adding the text "Red Colour...." at the coordinates (x, y), which corresponds to the top-left corner of the bounding rectangle for the detected red contour. The font used is cv2.FONT_HERSHEY_SIMPLEX, the font scale is set to 1.0, and the color of the text is red (0, 0, 255 in BGR format). By using this function, we can label the detected color regions in the image with descriptive text, making it easier to identify and understand what colors have been detected in each area of the image.
            #Just out of curiosity how are these functions implemented in the OpenCV library? I wonder if they are implemented in C++ and then wrapped in Python for ease of use, as is common with many performance-critical libraries. It would be interesting to look into the source code of OpenCV to see how these functions are implemented and optimized for performance, especially since they are widely used in real-time applications like video processing and computer vision tasks. Understanding the underlying implementation could provide insights into how these operations work and how we can further optimize our own code when using these functions in our projects.
            #Also interesting to see how the cv2 functions are defined and how they interact with the underlying data structures of images, such as NumPy arrays, to perform the necessary computations for tasks like drawing rectangles and adding text to images. This could give us a deeper understanding of how image processing works at a lower level (and boy do I love low level stuff) and how we can leverage these functions effectively in other applications.

    #creating contours to track green color
    contours, hierarchy = cv2.findContours(green_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
        area = cv2.contourArea(contour)
        if(area > 300):
            x, y, w, h = cv2.boundingRect(contour)
            imageFrame = cv2.rectangle(imageFrame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(imageFrame, "Yay Green Colour, hmm Hal Jordan? In Brightest day...", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 255, 0))

    #creating contours to track blue color
    contours, hierarchy = cv2.findContours(blue_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
        area = cv2.contourArea(contour)
        if(area > 300):
            x, y, w, h = cv2.boundingRect(contour)
            imageFrame = cv2.rectangle(imageFrame, (x, y), (x + w, y + h), (255, 0, 0), 2)
            cv2.putText(imageFrame, "Yay Blue Colour, hmm Nightwing? The boy wonder(Totally understand his obsession with starfire)", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 0, 0))


    #Running the program and displaying the results

    cv2.namedWindow("Multiple Color Detection in Real-Time", cv2.WND_PROP_FULLSCREEN)#(creates the window with fullscreen capability.)the namedWindow function is used to create a window with the specified name ("Multiple Color Detection in Real-Time") and properties (cv2.WND_PROP_FULLSCREEN). This allows us to display the results of our color detection in a full-screen window, providing a better visual experience when viewing the detected colors in real-time. By using this function, we can ensure that the window is created with the desired properties for optimal display of our color detection results.
    cv2.setWindowProperty("Multiple Color Detection in Real-Time", cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)#(forces it into fullscreen mode)the setWindowProperty function is used to set specific properties for the window we created with namedWindow. In this case, we are setting the property cv2.WND_PROP_FULLSCREEN to cv2.WINDOW_FULLSCREEN, which makes the window display in full-screen mode. This means that when we run the program, the window will take up the entire screen, allowing us to see the detected colors more clearly and without any distractions from other windows or elements on the screen. By using this function, we can enhance the visual presentation of our color detection results in real-time.
    #edit: this does not give me the full screen so debug later 🥲



    cv2.imshow("Multiple Color Detection in Real-TIme", imageFrame) #the imshow function is used to display the original image (imageFrame) with the detected colors highlighted. The first argument is the name of the window that will be created to display the image, and the second argument is the image itself. By using this function, we can visualize the results of our color detection in real-time, allowing us to see how the detected colors are highlighted in the original image as we process it.
    if cv2.waitKey(10) & 0xFF == ord('q'): #the waitKey function is used to wait for a key event for a specified amount of time (in this case, 10 milliseconds). The expression cv2.waitKey(10) & 0xFF is a common way to check if the 'q' key has been pressed. If the 'q' key is pressed, the condition will evaluate to True, and we can break out of the loop to stop the program. This allows us to have a way to exit the real-time color detection display by simply pressing the 'q' key on the keyboard.
        #After the loop, we should also release the webcam and close any OpenCV windows to clean up resources properly. This can be done with the following code:
        webcam.release() #releases the webcam resource
        cv2.destroyAllWindows() #closes all OpenCV windows
        break

